#!/usr/bin/python3
import requests
import bs4

## Use the requests library to grab the page
# Note sometimes you need to run this twice if it fails the first time
result = requests.get("https://en.wikipedia.org/wiki/Grace_Hopper")
#print(result.text)

##Pokazanie backendu strony w ladnych liniach, ulozone
soup = bs4.BeautifulSoup(result.text,"lxml")
#print(soup)

##Wyciagniecie 'title' z kodu strony
for item in soup.select('.vector-toc-text'):
        print(item.text)



