#!/usr/bin/python3
#jest tylko prawdziwe dla liczby 10-100 i 200 w zwyz
def almost_there(n):
    if n <= 100 or n>=200:
        return True
    else:
        return False
print(almost_there(10))
print(almost_there(105))
print(almost_there(209))
