#!/usr/bin/python3
#jest prawdziwe jesli sa obok siebie w liscie dwie 3
def has_33(num):
    for i in range(0, len(num)-1):
        if num[i] == 3 and num[i+1] ==3:
            return True
    return False
print(has_33([1,3,3]))
print(has_33([1,3,1,3]))
print(has_33([3,1,3]))
