#!/usr/bin/python3
#funckja gdzie bierze z listy liczby i zwraca TRUE jesli pojawia sie w liscie 007 
def spy_game(lists):
    code=[]
    for num in lists:
        if num == 0 or num ==7:
            code.append(num)
    return code == [0,0,7]
    
     
print(spy_game([1,2,4,0,0,7,5]))
print(spy_game([1,0,2,3,0,5,7]))
print(spy_game([1,7,2,0,4,5,0]))


