#!/usr/bin/python3
#zwraca liczbe liczb pierwszych w podanej liczbie 
def count_primes(num):
    primes=[]
    x=2
    if num <= 2:
        return 0
    while x <= num:
        for i in range(2,x):
            if x % i == 0:
                break
        else:
            primes.append(x)
        x += 1
    print(primes)
    return len(primes)

print(count_primes(100))
        
