#!/usr/bin/python3
#checks wheather number is in a given ranger, high and low 
def ran_check(num,low,high):
    if num in range(low,high+1):
        print(f'{num} is in the range between {low} and {high}')
    else: 
        print(f'The {num} is oustside the range {low} and  {high}')
print(ran_check(5,2,7))
print(ran_check(2,5,7))
