#!/usr/bin/python3
#calculate the number of upper and lower case in the text 
def num_upper_lower(text):
    d={'upper':0, 'lower':0}
   # return text.split()
    for char in text:
        if char.isupper():
            d['upper']+=1
        elif char.islower():
           d['lower']+=1
        else: 
            pass
    print(f'Original string is {text}')
    print(f'No of Upper case is {d["upper"]}')
    print(f'No of Lower case is {d["lower"]}')
print(num_upper_lower('Hello Mr. Rogers, how are you this fine Tuesday'))
