#!/usr/bin/python3
# pokazuje mniejsza jesli obie sa parzyste, pokazuje wieksza jak sa nieparzyste
def compare(num1, num2):
    if num1 %2 == 0 and num2 %2 ==0:
        return min(num1, num2)
    else:
        return max(num1,num2)
print(compare(2,5))
print(compare(2,4))
