#!/usr/bin/python3
# true is only when sum of two numbers gives 20
def makes_twenty(a,b):
    if (a+b) == 20 or a == 20 or b==20:
        return True 
    else: 
        return False
print(makes_twenty(20,10))
print(makes_twenty(12,8))
print(makes_twenty(1,3))



