#!/usr/bin/python3
#create bank account 

class Account():
    def __init__(self,owner,balance):
        self.balance= balance
        self.owner=owner
    def __str__(self):
        return f'Acount owner is {self.owner} with balance: {self.balance}'
   
    def deposit(self, dep):
        self.balance+= dep
        print('Deposit Added')
        
    def withdraw(self,wd):
        if self.balance >= wd:
            self.balance -= wd
            print('Withdrawal Added')
        else:
            print("Withdrawal deleted")
account1 = Account('Jose',100) 
print(account1)
print(account1.owner)
print(account1.balance)
print(account1.deposit(50))
print(account1.withdraw(75))
print(account1.withdraw(500))
