#!/usr/bin/env python3
import matplotlib.pyplot as plt

##initial values
#N0=0.150 #concentration of Nitrogen
N0=20
Xv0=2 #biomass,yeast
Xv0=2.0
S0=50 #sugar
E0=0.0 #concentration of ethanol

##parameters from table
mu_max=0.16
K_N=0.010
Y_XN=31.0
beta_max=0.3
K_S=10.0
Y_ES=0.47
k_d_prime=0.0001

##time frames 0-300 hours
t_start=0
t_end=300
dt=0.1
n_steps=int((t_end-t_start)/dt)

##initial list 
t_list=[]
N_list=[]
Xv_list=[]
S_list=[]
E_list=[]

#initial values 
N=N0
Xv=Xv0
S=S0
E=E0

##euler loop:
for i in range(n_steps+1):
	t=i*dt
	t_list.append(t)
	N_list.append(N)
	Xv_list.append(Xv)
	S_list.append(S)
	E_list.append(E)

	#kinetic equations
	mu = mu_max * N / (K_N + N) 
	kd = k_d_prime * E
	beta = beta_max * S / (K_S + S) 

	#equations for N,E,S
	dXv = (mu - kd) * Xv
	dN = -(mu * Xv) / Y_XN
	dE = beta * Xv
	dS = -(beta * Xv) / Y_ES

	#aktualizacja zmiennych
	Xv += dt * dXv
	N = max(-1000000, N + dt * dN)
	E = max(-1000000, E + dt * dE)
	S = max(-1000000, S + dt * dS)

#diagram
plt.plot(t_list, Xv_list, label='Xv (biomass)')
plt.plot(t_list, N_list, label='N (Nitrogen)')
plt.plot(t_list, S_list, label='S (Sugar)')
plt.plot(t_list, E_list, label='E (Ethanol)')
plt.xlabel('Time [h]')
plt.ylabel('Concentration [g/L]')
plt.title('Simulation via euler method')
plt.legend()
plt.grid(True)
plt.show()
