#!/usr/bin/python3
import requests
import bs4

##klasa dla ksiazki z 2 gwiazkami
#class="star-rating Two"
##nazwa klasy dla produktu
#product_pod

two_star_titles=[]
base_url='https://books.toscrape.com/catalogue/page-{}.html'

for n in range(1,51):

    scrape_url = base_url.format(n)
    res = requests.get(scrape_url)
    
    soup = bs4.BeautifulSoup(res.text,"lxml")
    books = soup.select(".product_pod")
    
    for book in books:
        if len(book.select('.star-rating.Two')) != 0:
            two_star_titles.append(book.select('a')[1]['title'])            
for title in two_star_titles:
    print(title)



