#!/usr/bin/python3
import csv
data=open('example.csv')
csv_data=csv.reader(data)
data_lines=list(csv_data)
#print(data_lines[0])

#for line in data_lines:
#    print(line)

#email from file
all_emails=[]
for line in data_lines:
    all_emails.append(line[3])
print(all_emails)
