#!/usr/bin/python3
from PIL import Image

mac=Image.open('example.jpg')
print(mac.size)
half=1993/2
x=half-200
w=half+200
y=800
h=1257
computer=mac.crop((x,y,w,h))
mac.paste(im=computer,box=(0,0))
resized=mac.resize((3000,500))
resized.show()
rotated=mac.rotate(90)
rotated.show()


