#!/usr/bin/python3
from PIL import Image

words=Image.open('word_matrix.png')
mask=Image.open('mask.png')
mask=mask.resize((1015,559))
mask.putalpha(200)
words.paste(im=mask,box=(0,0),mask=mask)
words.show()
