#!/usr/bin/python3
from PIL import Image
mac = Image.open('example.jpg')
mac.show()
print(f'Size is {mac.size}')
print(mac.filename)
print(mac.format_description)
cropped=mac.crop((0,0,100,100))
cropped.show()
