#!/usr/bin/env python3
import matplotlib.pyplot as plt
x = []
y = []

with open("data.csv", "r") as f:
    for line in f:
        line = line.strip()         
        if line:                    
            parts = line.split(",") 
            xi = float(parts[0])    
            yi = float(parts[1])    
            x.append(xi)
            y.append(yi)

print("x:", x)
print("y:", y)

x_mean = sum(x) / len(x)
y_mean = sum(y) / len(y)


numerator = sum((xi - x_mean) * (yi - y_mean) for xi, yi in zip(x, y))
denominator = sum((xi - x_mean)**2 for xi in x)
a = numerator / denominator

b = y_mean - a * x_mean

print(f"a = {a:.2f}, b = {b:.2f}")

x_line = [min(x), max(x)]
y_line = [a * xi + b for xi in x_line]

#coefficient
SSres = 0
for i in range(len(x)):
    yi = y[i]
    fi = a * x[i] + b  
    print(f"x={x[i]}, y={yi}, fi={fi:.2f}")  # <-- wypisywanie kolejnych fi
    SSres += (yi - fi)**2

SStot = 0
for yi in y:
    SStot += (yi - y_mean)**2

R2 = 1 - (SSres / SStot)

print(f"SSres = {SSres:.2f}")
print(f"SStot = {SStot:.2f}")
print(f"R^2 = {R2:.4f}")

plt.scatter(x, y, color='blue', label='Values')
plt.plot(x_line, y_line,color='red', label='Linear regression')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Linear regression: y = ax + b')
plt.legend()
plt.grid(True)
plt.show()

