#!/bin/python
import pylab as pl
x0=150       # set E
c=2
a=16807
m=2147483500
x_list=[]
pos=[]
walk=0

def Lehmer(x0,a,c,m):
    x=(x0*a+c)%m
    return x

for i in range(0,100000):
    x0=Lehmer(x0,a,c,m)
    x_list.append(x0)

    if x0 < m//2:
        walk-=1
    else:
        walk+=1
    pos.append(walk)

#repetition period (first return to the first generated value)
period=None
if x_list:
    first=x_list[0]
    for i,val in enumerate(x_list[1:], start=1):
        if val==first:
            period=i
            break
print("Repetition period:", period if period is not None else f"> {len(x_list)}")

#wykres
x_index_num = list(range(len(pos)))
pl.plot(x_index_num,pos,"b-")
pl.xlabel("steps taken")
pl.ylabel("left/right")
pl.title("Random walk (1D)")
pl.show()
